// FILE: src/spaces/promoteur/etudes/marche/config/poiCategories.ts

import { PoiCategory, PoiCategoryId } from "../types";

export const POI_CATEGORIES: Record<PoiCategoryId, PoiCategory> = {
  // Santé
  hospital: {
    id: "hospital",
    label: "Hôpital",
    labelPlural: "Hôpitaux",
    icon: "Hospital",
    color: "#dc2626",
    bpeCode: "D101",
  },
  emergency: {
    id: "emergency",
    label: "Urgences",
    labelPlural: "Urgences",
    icon: "Siren",
    color: "#dc2626",
    bpeCode: "D102",
  },
  pharmacy: {
    id: "pharmacy",
    label: "Pharmacie",
    labelPlural: "Pharmacies",
    icon: "Pill",
    color: "#16a34a",
    bpeCode: "D301",
  },
  general_practitioner: {
    id: "general_practitioner",
    label: "Médecin généraliste",
    labelPlural: "Médecins généralistes",
    icon: "Stethoscope",
    color: "#2563eb",
    bpeCode: "D201",
  },
  specialist: {
    id: "specialist",
    label: "Spécialiste",
    labelPlural: "Spécialistes",
    icon: "UserRound",
    color: "#7c3aed",
    bpeCode: "D2",
  },

  // Commerce
  supermarket: {
    id: "supermarket",
    label: "Supermarché",
    labelPlural: "Supermarchés",
    icon: "ShoppingCart",
    color: "#f59e0b",
    bpeCode: "B101",
  },
  grocery: {
    id: "grocery",
    label: "Épicerie",
    labelPlural: "Épiceries",
    icon: "Store",
    color: "#f59e0b",
    bpeCode: "B102",
  },
  bakery: {
    id: "bakery",
    label: "Boulangerie",
    labelPlural: "Boulangeries",
    icon: "Croissant",
    color: "#d97706",
    bpeCode: "B103",
  },
  bank: {
    id: "bank",
    label: "Banque",
    labelPlural: "Banques",
    icon: "Landmark",
    color: "#0891b2",
    bpeCode: "A206",
  },
  atm: {
    id: "atm",
    label: "Distributeur",
    labelPlural: "Distributeurs",
    icon: "CreditCard",
    color: "#0891b2",
    bpeCode: "A207",
  },
  post_office: {
    id: "post_office",
    label: "Bureau de poste",
    labelPlural: "Bureaux de poste",
    icon: "Mail",
    color: "#eab308",
    bpeCode: "A203",
  },
  gas_station: {
    id: "gas_station",
    label: "Station service",
    labelPlural: "Stations service",
    icon: "Fuel",
    color: "#64748b",
    bpeCode: "B201",
  },

  // Sécurité
  police: {
    id: "police",
    label: "Commissariat",
    labelPlural: "Commissariats",
    icon: "Shield",
    color: "#1e40af",
    bpeCode: "A105",
  },
  gendarmerie: {
    id: "gendarmerie",
    label: "Gendarmerie",
    labelPlural: "Gendarmeries",
    icon: "Shield",
    color: "#1e40af",
    bpeCode: "A104",
  },
  fire_station: {
    id: "fire_station",
    label: "Pompiers",
    labelPlural: "Casernes pompiers",
    icon: "Flame",
    color: "#dc2626",
    bpeCode: "A106",
  },

  // Éducation
  school_primary: {
    id: "school_primary",
    label: "École primaire",
    labelPlural: "Écoles primaires",
    icon: "School",
    color: "#8b5cf6",
    bpeCode: "C1",
  },
  school_secondary: {
    id: "school_secondary",
    label: "Collège",
    labelPlural: "Collèges",
    icon: "GraduationCap",
    color: "#7c3aed",
    bpeCode: "C2",
  },
  high_school: {
    id: "high_school",
    label: "Lycée",
    labelPlural: "Lycées",
    icon: "GraduationCap",
    color: "#6d28d9",
    bpeCode: "C3",
  },
  university: {
    id: "university",
    label: "Université",
    labelPlural: "Universités",
    icon: "University",
    color: "#5b21b6",
    bpeCode: "C5",
  },
  daycare: {
    id: "daycare",
    label: "Crèche",
    labelPlural: "Crèches",
    icon: "Baby",
    color: "#ec4899",
    bpeCode: "D502",
  },

  // Transport
  bus_stop: {
    id: "bus_stop",
    label: "Arrêt de bus",
    labelPlural: "Arrêts de bus",
    icon: "Bus",
    color: "#0ea5e9",
    osmTag: "highway=bus_stop",
  },
  train_station: {
    id: "train_station",
    label: "Gare",
    labelPlural: "Gares",
    icon: "Train",
    color: "#0284c7",
    bpeCode: "E102",
  },
  metro: {
    id: "metro",
    label: "Métro",
    labelPlural: "Stations métro",
    icon: "TrainFront",
    color: "#0369a1",
    osmTag: "railway=subway_entrance",
  },
  parking: {
    id: "parking",
    label: "Parking",
    labelPlural: "Parkings",
    icon: "ParkingCircle",
    color: "#64748b",
    osmTag: "amenity=parking",
  },

  // Restauration & hébergement
  restaurant: {
    id: "restaurant",
    label: "Restaurant",
    labelPlural: "Restaurants",
    icon: "Utensils",
    color: "#ea580c",
    bpeCode: "B203",
  },
  hotel: {
    id: "hotel",
    label: "Hôtel",
    labelPlural: "Hôtels",
    icon: "Hotel",
    color: "#6366f1",
    bpeCode: "F310",
  },

  // Établissements spécialisés
  ehpad: {
    id: "ehpad",
    label: "EHPAD",
    labelPlural: "EHPAD",
    icon: "Heart",
    color: "#ec4899",
    bpeCode: "D503",
  },
  rss: {
    id: "rss",
    label: "Résidence seniors",
    labelPlural: "Résidences seniors",
    icon: "Users",
    color: "#10b981",
  },
  student_residence: {
    id: "student_residence",
    label: "Résidence étudiante",
    labelPlural: "Résidences étudiantes",
    icon: "Building",
    color: "#8b5cf6",
  },
  coworking: {
    id: "coworking",
    label: "Coworking",
    labelPlural: "Espaces coworking",
    icon: "Laptop",
    color: "#64748b",
  },
  congress_center: {
    id: "congress_center",
    label: "Centre de congrès",
    labelPlural: "Centres de congrès",
    icon: "Presentation",
    color: "#6366f1",
  },

  // Loisirs
  sports: {
    id: "sports",
    label: "Équipement sportif",
    labelPlural: "Équipements sportifs",
    icon: "Dumbbell",
    color: "#22c55e",
    bpeCode: "F1",
  },
  cinema: {
    id: "cinema",
    label: "Cinéma",
    labelPlural: "Cinémas",
    icon: "Film",
    color: "#a855f7",
    bpeCode: "F303",
  },
  library: {
    id: "library",
    label: "Bibliothèque",
    labelPlural: "Bibliothèques",
    icon: "BookOpen",
    color: "#0891b2",
    bpeCode: "F305",
  },
  park: {
    id: "park",
    label: "Parc / Jardin",
    labelPlural: "Parcs et jardins",
    icon: "Trees",
    color: "#22c55e",
    osmTag: "leisure=park",
  },
};