import { supabase } from '@/lib/supabaseClient';
import { parseFollowup, type Followup } from '@shared/project-followup/model';
export type SavedFollowup={project_key:string;title:string;payload:Followup;revision:number;updated_at:string};
let pendingSelection:{uid:string;id:string}|null=null;
export function pendingFolder(uid:string):string|null{return pendingSelection?.uid===uid?pendingSelection.id:null;}
export function clearPendingFolder(){pendingSelection=null;}
export async function listFollowups():Promise<SavedFollowup[]>{const {data,error}=await supabase.from('project_followups').select('project_key,title,payload,revision,updated_at').order('updated_at',{ascending:false});if(error)throw new Error(error.message);return (data??[]).flatMap(r=>{const payload=parseFollowup(r.payload);return payload?[{...r,payload}]:[];});}
export async function saveFollowup(key:string,title:string,payload:unknown,revision:number):Promise<SavedFollowup>{const parsed=parseFollowup(payload);if(!parsed)throw new Error('Le suivi proposé contient des données invalides.');const {data,error}=await supabase.rpc('save_project_followup',{p_project_key:key,p_title:title,p_payload:parsed,p_revision:revision});if(error)throw new Error(error.message);if(!data?.[0])throw new Error('Enregistrement non confirmé.');window.dispatchEvent(new Event('mzia-followup-changed'));return {...data[0],payload:parsed};}
export function folderStore(uid:string):{projects:{id:string;name:string;color:string}[];assignments:Record<string,string>}{try{const s=JSON.parse(localStorage.getItem(`u:${uid}:mzia.projects`)??'{}');return{projects:Array.isArray(s.projects)?s.projects:[],assignments:s.assignments??{}};}catch{return{projects:[],assignments:{}};}}
export function chooseFolder(uid:string,id:string,title:string,conversationId:string|null){const s=folderStore(uid);if(!s.projects.some(p=>p.id===id))s.projects.push({id,name:title,color:'#6d5dfc'});if(conversationId)s.assignments[conversationId]=id;pendingSelection={uid,id};localStorage.setItem(`u:${uid}:mzia.projects`,JSON.stringify(s));window.dispatchEvent(new Event('mzia-projects-changed'));}
export async function followupContext(conversationId:string|null):Promise<Record<string,unknown>|null>{const {data}=await supabase.auth.getUser();if(!data.user)return null;const s=folderStore(data.user.id),id=conversationId?s.assignments[conversationId]:pendingFolder(data.user.id);if(!id)return null;const key=`folder:${id}`;const rows=await listFollowups();const row=rows.find(r=>r.project_key===key);return row?{project_key:key,title:row.title,revision:row.revision,updated_at:row.updated_at,payload:row.payload}:{project_key:key,title:s.projects.find(p=>p.id===id)?.name??'Dossier',revision:0,payload:null};}
