import { useCallback, useEffect, useRef, useState } from 'react';
import { supabase } from '@/lib/supabaseClient';
import { emptyFollowup, followupIndicators, parseFollowup, STAGES, STAGE_LABELS, type Followup, type FollowupTask } from '@shared/project-followup/model';
import { chooseFolder, folderStore, listFollowups, saveFollowup, pendingFolder, clearPendingFolder, type SavedFollowup } from './followupRepository';
import './followup.css';
const today=()=>new Intl.DateTimeFormat('fr-CA',{timeZone:'Europe/Paris'}).format(new Date());
const statuses={a_faire:'À faire',en_cours:'En cours',attente:'En attente',termine:'Terminé'};
export function FollowupPanel({conversationId,onSend,isStreaming}:{conversationId:string|null;onSend:(s:string)=>void;isStreaming:boolean}){
  const [uid,setUid]=useState(''),[folders,setFolders]=useState<{id:string;name:string}[]>([]),[rows,setRows]=useState<SavedFollowup[]>([]),[key,setKey]=useState(''),[name,setName]=useState(''),[draft,setDraft]=useState<Followup>(emptyFollowup),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[dirty,setDirty]=useState(false),[opened,setOpened]=useState(false);
  const identity=useRef(0);
  const previousConversation=useRef<string|null>(conversationId);
  const refresh=useCallback(async()=>{const token=++identity.current;const {data}=await supabase.auth.getUser();if(token!==identity.current)return;const user=data.user?.id??'';setUid(user);if(!user){setRows([]);setFolders([]);setKey('');setDraft(emptyFollowup());return;}const s=folderStore(user);setFolders(s.projects);try{const saved=await listFollowups();if(token===identity.current)setRows(saved);}catch{if(token===identity.current)setNotice('Le suivi n’a pas pu être chargé. Réessayez avant de modifier le dossier.');}},[]);
  useEffect(()=>{void refresh();const changed=()=>void refresh();window.addEventListener('mzia-projects-changed',changed);window.addEventListener('mzia-followup-changed',changed);const {data}=supabase.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){clearPendingFolder();setKey('');setDraft(emptyFollowup());setDirty(false);}void refresh();});return()=>{identity.current++;data.subscription.unsubscribe();window.removeEventListener('mzia-projects-changed',changed);window.removeEventListener('mzia-followup-changed',changed);};},[refresh]);
  const choices=[...folders.map(p=>({key:`folder:${p.id}`,title:p.name})),...rows.filter(r=>!folders.some(f=>`folder:${f.id}`===r.project_key)).map(r=>({key:r.project_key,title:r.title}))];
  const select=useCallback((next:string)=>{const row=rows.find(r=>r.project_key===next);setKey(next);setDraft(row?.payload??emptyFollowup());setRevision(row?.revision??0);setDirty(false);setNotice('');if(uid&&next.startsWith('folder:'))chooseFolder(uid,next.slice(7),row?.title??folders.find(f=>`folder:${f.id}`===next)?.name??'Dossier',conversationId);},[rows,uid,folders,conversationId]);
  useEffect(()=>{if(!uid)return;const pending=pendingFolder(uid);if(conversationId&&!previousConversation.current&&pending)chooseFolder(uid,pending,folderStore(uid).projects.find(p=>p.id===pending)?.name??'Dossier',conversationId);if(!conversationId)clearPendingFolder();previousConversation.current=conversationId;const assigned=conversationId?folderStore(uid).assignments[conversationId]:null;const next=assigned?`folder:${assigned}`:'';setKey(next);const row=rows.find(r=>r.project_key===next);setDraft(row?.payload??emptyFollowup());setRevision(row?.revision??0);setDirty(false);},[conversationId,uid]);
  useEffect(()=>{if(!key||dirty)return;const row=rows.find(r=>r.project_key===key);setDraft(row?.payload??emptyFollowup());setRevision(row?.revision??0);},[rows,key,dirty]);
  useEffect(()=>{const changed=()=>{if(!uid||!conversationId)return;const assigned=folderStore(uid).assignments[conversationId];const next=assigned?`folder:${assigned}`:'';if(next===key)return;if(dirty){setNotice('Le dossier de cette conversation a changé. Enregistrez ou rechargez votre suivi avant de poursuivre.');return;}setKey(next);};window.addEventListener('mzia-projects-changed',changed);return()=>window.removeEventListener('mzia-projects-changed',changed);},[uid,conversationId,key,dirty]);
  useEffect(()=>{const proposal=(e:Event)=>{const v=(e as CustomEvent).detail;const p=parseFollowup(v?.payload);if(!p||!uid)return;const assigned=conversationId?folderStore(uid).assignments[conversationId]:null;if(!assigned||v.project_key!==`folder:${assigned}`){setNotice('La proposition concerne un autre dossier. Sélectionnez sa conversation avant de l’enregistrer.');setOpened(true);return;}setKey(v.project_key);setDraft(p);setRevision(v.revision);setDirty(true);setOpened(true);setNotice('Proposition IA à vérifier : aucune modification enregistrée.');};window.addEventListener('mzia-followup-proposal',proposal);return()=>window.removeEventListener('mzia-followup-proposal',proposal);},[uid,conversationId]);
  const edit=(patch:Partial<Followup>)=>{setDraft(d=>({...d,...patch}));setDirty(true);setNotice('Modifications à enregistrer.');};
  const task=(id:string,patch:Partial<FollowupTask>)=>edit({tasks:draft.tasks.map(t=>t.id===id?{...t,...patch}:t)});
  const title=choices.find(c=>c.key===key)?.title??name;
  const indicators=followupIndicators(draft,today());
  const save=async()=>{if(!uid||!key||busy)return;setBusy(true);try{const row=await saveFollowup(key,title,draft,revision);setRevision(row.revision);setDraft(row.payload);setDirty(false);setNotice('Suivi enregistré dans ce dossier.');await refresh();}catch(e){setNotice(e instanceof Error?e.message:'Enregistrement impossible.');}finally{setBusy(false);}};
  return <section className="mzia-followup" aria-label="Suivi de projet"><button className="mzia-followup-toggle" type="button" onClick={()=>setOpened(!opened)} aria-expanded={opened}>Suivi de projet {key?`· ${title}`:''} {dirty?'· à enregistrer':''}</button>{opened&&<div>
    <p>Informations déclarées par l’acheteur. L’IA distingue les faits enregistrés et ses recommandations. Une tâche terminée ne valide pas juridiquement une étape.</p>
    {!uid?<p>Connectez-vous pour enregistrer un suivi.</p>:<>
    <label>Dossier du suivi<select aria-label="Dossier du suivi" value={key} disabled={busy||isStreaming} onChange={e=>{if(!dirty||window.confirm("Abandonner les modifications non enregistrées ?"))select(e.target.value);}}><option value="">Choisir un dossier</option>{choices.map(c=><option key={c.key} value={c.key}>{c.title}</option>)}</select></label>
    <div className="mzia-followup-create"><input aria-label="Nom du nouveau dossier de suivi" placeholder="Nom du nouveau dossier" value={name} maxLength={200} onChange={e=>setName(e.target.value)}/><button type="button" disabled={!name.trim()||busy||isStreaming} onClick={()=>{const id=crypto.randomUUID();chooseFolder(uid,id,name.trim(),conversationId);setFolders(folderStore(uid).projects);setKey(`folder:${id}`);setDraft(emptyFollowup());setRevision(0);setDirty(true);setOpened(true);}}>Créer le dossier</button></div>
    {key&&<><div className="mzia-followup-grid"><label>Étape déclarée<select aria-label="Étape déclarée" value={draft.stage} onChange={e=>edit({stage:e.target.value as Followup['stage']})}>{STAGES.map(s=><option key={s} value={s}>{STAGE_LABELS[s]}</option>)}</select></label><label>Situation actuelle<textarea value={draft.summary} maxLength={2000} onChange={e=>edit({summary:e.target.value})} placeholder="Ex. promesse signée ; offre bancaire attendue"/></label></div>
    <label>Pièces ou informations manquantes · une par ligne<textarea value={draft.missing.join('\n')} onChange={e=>edit({missing:e.target.value.split('\n').slice(0,30)})} placeholder="Règlement PLU écrit, devis VRD, accord de financement…"/></label>
    <p className="mzia-followup-stats">{indicators.open} tâche(s) ouverte(s) · {indicators.done} terminée(s) · {indicators.blocked} blocage(s) · {indicators.overdue.length} échéance(s) dépassée(s)</p>
    {draft.tasks.map(t=><fieldset key={t.id}><legend>{t.title||'Nouvelle tâche'}</legend><label>Action attendue<input value={t.title} maxLength={200} onChange={e=>task(t.id,{title:e.target.value})}/></label><div className="mzia-followup-grid"><label>Statut<select aria-label="Statut" value={t.status} onChange={e=>task(t.id,{status:e.target.value as FollowupTask['status']})}>{Object.entries(statuses).map(([s,label])=><option key={s} value={s}>{label}</option>)}</select></label><label>Responsable / interlocuteur<input value={t.owner} maxLength={120} onChange={e=>task(t.id,{owner:e.target.value})} placeholder="Nom ou rôle à préciser"/></label><label>Échéance<input type="date" value={t.dueDate} onChange={e=>task(t.id,{dueDate:e.target.value})}/></label><label>Dernier contact déclaré<input type="date" value={t.lastContactDate} onChange={e=>task(t.id,{lastContactDate:e.target.value})}/></label></div><label>Notes / réponse reçue<textarea value={t.notes} maxLength={1000} onChange={e=>task(t.id,{notes:e.target.value})}/></label><label><input type="checkbox" checked={t.blocking} onChange={e=>task(t.id,{blocking:e.target.checked})}/> Bloque la prochaine étape</label><div className="mzia-followup-actions"><button type="button" disabled={dirty||isStreaming} onClick={()=>onSend(`À partir du suivi enregistré du dossier, prépare une relance pour ${t.owner||'l’interlocuteur à préciser'} concernant « ${t.title} ». Rappelle la pièce ou réponse attendue et propose un message à copier. Ne l’envoie pas et n’invente aucun contact ni délai légal.`)}>Préparer une relance</button><button type="button" onClick={()=>edit({tasks:draft.tasks.filter(x=>x.id!==t.id)})}>Retirer la tâche</button></div></fieldset>)}
    <div className="mzia-followup-actions"><button type="button" disabled={draft.tasks.length>=50} onClick={()=>edit({tasks:[...draft.tasks,{id:crypto.randomUUID(),title:'Nouvelle tâche',status:'a_faire',owner:'',dueDate:'',lastContactDate:'',blocking:false,notes:''}]})}>Ajouter une tâche</button><button type="button" disabled={busy||!dirty||isStreaming} onClick={()=>void save()}>Enregistrer dans le dossier</button><button type="button" disabled={busy||isStreaming} onClick={()=>{select(key);void refresh();}}>Recharger le suivi enregistré</button><button type="button" disabled={dirty||isStreaming||revision===0} onClick={()=>onSend('Consulte le suivi enregistré de ce dossier. Dis où en est le projet, ce qui manque, les blocages, les prochaines actions et qui relancer. Distingue échéances déclarées et délais légaux. Propose une mise à jour du suivi uniquement à partir des faits connus.')}>Faire le point avec l’IA</button></div>
    {dirty&&<small>Enregistrez vos modifications pour que l’IA dispose du suivi à jour.</small>}
    </>}
    </>}{notice&&<p role="status">{notice}</p>}
  </div>}</section>;
}
