export const TERTIARY_PROGRAMMES = [
  { id:'office', label:'Bureaux', target:'PME, professions de services et entreprises en implantation ou regroupement', market:['Demande placée par taille et qualité de surface', 'Offre immédiatement disponible, vacance et projets concurrents', 'Loyers signés HT HC/an, franchises et travaux preneur'], design:['Plateaux divisibles, lumière naturelle et confort acoustique', 'Transports, stationnement, accès PMR et services utiles aux salariés', 'Flexibilité des réseaux, sobriété énergétique et coût des charges'], buyers:'Utilisateurs en acquisition, investisseurs et foncières selon le bail et la qualité du locataire' },
  { id:'retail', label:'Commerces', target:'Enseignes et commerçants dont le format répond aux flux et à la chalandise du site', market:['Flux piétons et véhicules, visibilité et accessibilité', 'Chalandise, dépenses captables, concurrence et cellules vacantes', 'Loyers, charges, droit au bail éventuel et effort locatif supportable'], design:['Vitrine, linéaire de façade et parcours client', 'Surface de vente, réserves, livraisons et déchets', 'Accès clients, stationnement et adaptations au format de l’enseigne'], buyers:'Enseignes utilisatrices, commerçants et investisseurs de murs commerciaux' },
  { id:'activity', label:'Locaux d’activité', target:'Artisans, PME de production, maintenance, stockage et distribution à qualifier par métier', market:['Demandes d’implantation ou d’extension par activité et taille de lot', 'Offre de locaux, loyers signés, vacance et disponibilité foncière', 'Bassin d’emploi, fournisseurs, desserte routière et besoins techniques'], design:['Hauteur libre, portes sectionnelles et charge au sol', 'Puissance électrique, ventilation et part de bureaux utile', 'Accès poids lourds, manœuvres, livraisons et divisibilité des lots'], buyers:'Entreprises occupantes, investisseurs de parcs d’activité et foncières spécialisées' },
] as const;
export type TertiaryKind = typeof TERTIARY_PROGRAMMES[number]['id'];
export type RentalInputs = { surfaceM2:string; rentAnnualM2:string; vacancyPct:string; annualOwnerCosts:string; totalInvestment:string; exitYieldPct:string };
export const emptyRentalInputs = ():RentalInputs => ({surfaceM2:'',rentAnnualM2:'',vacancyPct:'',annualOwnerCosts:'',totalInvestment:'',exitYieldPct:''});
const parse = (v:string) => v.trim() !== '' && Number.isFinite(Number(v.replace(',','.'))) ? Number(v.replace(',','.')) : null;
export function calculateTertiaryRental(input:RentalInputs) {
  const surface=parse(input.surfaceM2),rent=parse(input.rentAnnualM2),vacancy=parse(input.vacancyPct),costs=parse(input.annualOwnerCosts),investment=parse(input.totalInvestment),yieldPct=parse(input.exitYieldPct);
  if(surface == null || surface <= 0 || rent == null || rent < 0 || vacancy == null || vacancy < 0 || vacancy > 100 || costs == null || costs < 0 || investment == null || investment <= 0) return null;
  const gross=surface*rent,effective=gross*(1-vacancy/100),net=effective-costs;
  const valuation = yieldPct != null && yieldPct > 0 && yieldPct <= 100 && net > 0 ? net/(yieldPct/100) : null;
  return {gross,effective,net,netYieldPct:net/investment*100,valuation,
    sensitivities:[{label:'Loyer −10 %',net:effective*.9-costs},{label:'Vacance +10 points (maximum 100 %)',net:gross*(1-Math.min(100,vacancy+10)/100)-costs}]};
}
export function buildTertiaryBrief(input:{location:string; surface:string; programme:string; exit:string; needs:string; financial:RentalInputs}) {
  const profile=TERTIARY_PROGRAMMES.find(p=>p.label===input.programme);
  const calculation=calculateTertiaryRental(input.financial);
  return [
    `Étudie un projet d’immobilier d’entreprise : ${input.programme}. Terrain : ${input.location || 'localisation à préciser'} ; surface de terrain déclarée : ${input.surface || 'inconnue'} m².`,
    `Sortie envisagée : ${input.exit}. Besoins utilisateurs déclarés : ${input.needs.trim() || 'aucun utilisateur confirmé'}.`,
    'Commence par vérifier la localisation et les destinations autorisées au PLU, les risques et les servitudes avec les API existantes. Distingue surface du terrain, surface de plancher et surface utile locative.',
    `Cible à qualifier : ${profile?.target ?? 'utilisateurs d’immobilier d’entreprise'}. Marché à documenter : ${profile?.market.join(' ; ') ?? 'demande, concurrence, loyers et vacance propres à cet usage'}. Programme technique : ${profile?.design.join(' ; ') ?? 'besoins techniques à recueillir'}.`,
    'Complète avec la recherche Internet et des sources datées : INSEE/Sirene pour le tissu économique, Sitadel pour les locaux non résidentiels autorisés, observatoires CCI et publications de conseils en immobilier d’entreprise pour le marché du bassin. Donne le périmètre, la période et le lien de chaque source. Une statistique nationale ou régionale ne devient pas une mesure locale.',
    'Distingue loyers demandés, loyers signés et loyers économiques après franchises ; ventes à utilisateur et investissement ; demande placée et simple présence d’entreprises. N’utilise pas une médiane DVF résidentielle pour valoriser des bureaux, commerces ou locaux d’activité. Aucun hôtel, EHPAD ou logement ne fait partie de cette comparaison.',
    'Pour les locaux d’activité, aucun modèle spécialisé n’est branché actuellement : ne substitue pas le score bureaux ou commerce. Recherche les données sectorielles, indique les lacunes et recueille les exigences techniques des entreprises.',
    calculation ? `Hypothèses financières fournies, non validées par le marché : surface utile locative ${input.financial.surfaceM2} m² ; loyer ${input.financial.rentAnnualM2} €/m²/an HT HC ; vacance ${input.financial.vacancyPct} % ; coûts annuels propriétaire non récupérables ${input.financial.annualOwnerCosts} € ; coût total d’investissement ${input.financial.totalInvestment} € ; taux de capitalisation ${input.financial.exitYieldPct || 'non fourni'} %. Simulation avant financement et impôt : revenu net annuel ${calculation.net} €, rendement net ${calculation.netYieldPct} %. La capitalisation simplifiée n’est pas une expertise de valeur et n’intègre pas les frais de cession, franchises initiales ou travaux futurs.` : 'Hypothèses financières incomplètes : liste les chiffres nécessaires, ne chiffre aucune valeur de sortie ou marge par défaut.',
    `Acquéreurs à qualifier : ${profile?.buyers ?? 'utilisateurs et investisseurs'}. Propose des entreprises seulement avec sources vérifiables et pertinence démontrée ; leur présence ou un code NAF ne prouve pas un besoin ni un intérêt.`,
    'Rends un dossier : demande et concurrence, meilleure cible et raisons sourcées, 2 ou 3 variantes de lots et programme technique conditionnel, PLU et points bloquants, économie et sensibilités, précommercialisation, profils de décideurs à viser et pièces à leur remettre. Conclus par une priorité conditionnelle ou une absence de choix si les preuves ne suffisent pas.'
  ].join('\n\n');
}
