import { useEffect, useState } from 'react';
import { userStorage } from '@/lib/storage/userScopedStorage';
import { useCopilot } from '@/spaces/copilot/hooks/useCopilot';
import { TERTIARY_PROGRAMMES, buildTertiaryBrief, calculateTertiaryRental, emptyRentalInputs, type RentalInputs } from './tertiaryStrategy';
const fmt=(n:number)=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(n);
export function TertiaryStrategySection({programme,onProgramme,location,terrainSurface,studyId,onBriefChange}:{programme:string;onProgramme:(value:string)=>void;location:string;terrainSurface:string;studyId:string|null;onBriefChange?:(value:string)=>void}) {
  const key=`mimmoza.promoteur.tertiaire.${studyId ?? 'hors-etude'}`;
  const [exit,setExit]=useState('Location puis cession à un investisseur');
  const [needs,setNeeds]=useState('');
  const [financial,setFinancial]=useState<RentalInputs>(emptyRentalInputs);
  const [loadedKey,setLoadedKey]=useState('');
  const {sendMessage,openCopilot,isStreaming}=useCopilot();
  useEffect(()=>{setLoadedKey('');try{const raw=JSON.parse(userStorage.getItem(key)??'null');setExit(typeof raw?.exit==='string'?raw.exit:'Location puis cession à un investisseur');setNeeds(typeof raw?.needs==='string'?raw.needs:'');setFinancial(Object.fromEntries(Object.keys(emptyRentalInputs()).map(k=>[k,typeof raw?.financial?.[k]==='string'?raw.financial[k]:''])) as RentalInputs);}catch{setNeeds('');setFinancial(emptyRentalInputs());}setLoadedKey(key);},[key]);
  useEffect(()=>{if(loadedKey===key)userStorage.setItem(key,JSON.stringify({exit,needs,financial}));},[key,loadedKey,exit,needs,financial]);
  const result=calculateTertiaryRental(financial);
  const chosen=TERTIARY_PROGRAMMES.find(p=>p.label===programme);
  const brief=buildTertiaryBrief({location,surface:terrainSurface,programme:chosen?.label??'Bureaux, commerces et locaux d’activité',exit,needs,financial});
  useEffect(()=>{onBriefChange?.(brief);},[brief,onBriefChange]);
  const field=(name:keyof RentalInputs,label:string)=> <label className="text-sm text-slate-700">{label}<input type="number" min="0" max={name==='vacancyPct'||name==='exitYieldPct'?100:undefined} step="any" value={financial[name]} onChange={e=>setFinancial(prev=>({...prev,[name]:e.target.value}))} className="mt-1 w-full rounded-xl border border-slate-300 p-2.5" /></label>;
  return <section className="rounded-3xl border border-indigo-200 bg-white p-5 sm:p-7" aria-label="Cadrage immobilier d’entreprise"><p className="text-xs font-bold uppercase tracking-widest text-indigo-700">IMMOBILIER D’ENTREPRISE</p><h2 className="mt-1 text-2xl font-semibold text-slate-950">Quel produit pour quels utilisateurs ?</h2><p className="mt-2 text-sm text-slate-600">Qualifier les besoins, le marché locatif, les caractéristiques techniques et la sortie avant de figer le bâtiment.</p>
    <div className="mt-5 grid gap-4 lg:grid-cols-3">{TERTIARY_PROGRAMMES.map(p=><article key={p.id} className={`rounded-2xl border p-4 ${programme===p.label?'border-indigo-500 bg-indigo-50':'border-slate-200'}`}><h3 className="font-semibold text-slate-900">{p.label}</h3><p className="mt-2 text-sm text-slate-700"><strong>Utilisateurs :</strong> {p.target}.</p><h4 className="mt-4 text-sm font-semibold">Marché à mesurer</h4><ul className="mt-2 list-inside list-disc space-y-1 text-xs text-slate-600">{p.market.map(s=><li key={s}>{s}</li>)}</ul><h4 className="mt-4 text-sm font-semibold">Programme technique</h4><ul className="mt-2 list-inside list-disc space-y-1 text-xs text-slate-600">{p.design.map(s=><li key={s}>{s}</li>)}</ul><p className="mt-3 text-xs text-slate-600"><strong>Sortie :</strong> {p.buyers}.</p><button type="button" aria-pressed={programme===p.label} onClick={()=>onProgramme(p.label)} className="mt-4 rounded-xl border border-indigo-300 px-3 py-2 text-sm font-semibold text-indigo-700">Étudier {p.label.toLowerCase()}</button></article>)}</div>
    <div className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-slate-700">Stratégie de sortie<select value={exit} onChange={e=>setExit(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 p-2.5"><option>Location puis cession à un investisseur</option><option>Vente à un utilisateur</option><option>Vente de lots à plusieurs utilisateurs</option><option>Conservation patrimoniale en location</option><option>Cession du foncier ou du projet autorisé</option></select></label><label className="text-sm font-medium text-slate-700">Besoins ou contacts utilisateurs<textarea value={needs} onChange={e=>setNeeds(e.target.value)} maxLength={3000} rows={3} placeholder="Métiers, surfaces, calendrier, budget locatif, cahier des charges, intérêt écrit…" className="mt-1 w-full rounded-xl border border-slate-300 p-2.5 font-normal" /></label></div>
    <details className="mt-6 rounded-2xl border border-slate-200 p-4"><summary className="cursor-pointer font-semibold text-slate-900">Tester l’économie locative du projet</summary><p className="mt-2 text-xs text-slate-600">Montants HT ou nets de TVA récupérable. Renseigner tous les postes, y compris un zéro explicite. Surface utile locative distincte du terrain. Simulation annuelle stabilisée avant financement et impôt ; franchises, travaux futurs et frais de cession à instruire séparément.</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{field('surfaceM2','Surface utile locative (m²)')}{field('rentAnnualM2','Loyer annuel HT HC (€/m²/an)')}{field('vacancyPct','Vacance économique hypothétique (%)')}{field('annualOwnerCosts','Charges propriétaire non récupérables (€/an)')}{field('totalInvestment','Coût complet d’investissement (€)')}{field('exitYieldPct','Taux de capitalisation de sortie (%) · facultatif')}</div>
      {result?<><dl className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Loyers théoriques / an',`${fmt(result.gross)} €`],['Revenu net / an',`${fmt(result.net)} €`],['Rendement net sur coût',`${result.netYieldPct.toFixed(2)} %`],['Valeur par capitalisation',result.valuation==null?'Taux positif et revenu net positif requis':`${fmt(result.valuation)} €`]].map(([label,value])=><div key={label} className="rounded-xl bg-indigo-50 p-3"><dt className="text-xs text-indigo-800">{label}</dt><dd className="mt-1 font-semibold text-indigo-950">{value}</dd></div>)}</dl><p className="mt-3 text-sm text-slate-600">Sensibilité du revenu net annuel : {result.sensitivities.map(s=>`${s.label} : ${fmt(s.net)} €`).join(' · ')}.</p><p className="mt-2 text-xs text-slate-500">Capitalisation simplifiée = revenu net / taux. Ce montant n’est ni un prix de vente confirmé ni une marge promoteur.</p></>:<p className="mt-4 text-sm text-amber-800">Complétez les cinq hypothèses obligatoires pour calculer. Aucun loyer, taux ou coût de marché n’est ajouté par défaut.</p>}
    </details>
    <div className="mt-5 flex flex-wrap gap-3"><button type="button" disabled={isStreaming||!location.trim()} onClick={()=>{openCopilot();void sendMessage(brief,{vertical:'promoteur'});}} className="rounded-xl bg-indigo-700 px-5 py-3 font-semibold text-white disabled:opacity-50">Construire le dossier tertiaire avec l’IA</button></div><p className="mt-2 text-xs text-slate-500">Le brief, la localisation et vos hypothèses seront envoyés au tchat. L’analyse utilise les outils existants et la recherche Internet ; son coût suit votre offre. {!location.trim()?'Renseignez la localisation du terrain ci-dessous.':''}</p>
    <details className="mt-4"><summary className="cursor-pointer text-sm font-semibold text-indigo-700">Voir le brief envoyé à l’IA</summary><pre className="mt-3 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-700">{brief}</pre></details>
    <p className="mt-5 text-xs text-slate-600">Sources à instruire : <a href="https://www.immostat.com/infos-marches/" target="_blank" rel="noopener noreferrer" className="underline">ImmoStat · indicateurs et périmètres disponibles</a> · <a href="https://www.data.gouv.fr/datasets/locaux-non-residentiels-autorises-et-commences-en-series-annuelles" target="_blank" rel="noopener noreferrer" className="underline">Sitadel · locaux non résidentiels</a>. Ces liens ne constituent pas une collecte automatique de loyers locaux. Les besoins et conditions des utilisateurs exigent des preuves propres au projet.</p>
  </section>;
}
